# Deployment job

name: env variables
permissions: read-all

on: page_build

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        env:
          MAPS_KEY: ${{ secrets.MAPS_KEY }}
          WEATHER_KEY: ${{ secrets.WEATHER_KEY }}
        run: |
          echo $MAPS_KEY $WEATHER_KEY 
