# Deployment job

name: env variables
permissions: read-all

on: page_build

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://github.com
    steps:
      - name: deploy
        env:
          MAPS_KEY: ${{ secrets.MAPS_KEY }}
          WEATHER_KEY: ${{ secrets.WEATHER_KEY }}
        run: |
          echo $MAPS_KEY $WEATHER_KEY 
