# Deployment job

name: env variables
permissions: read-all

on: page_build

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: deploy
        run: |
          echo run
          npm install dotenv
          echo $MAPS_KEY $WEATHER_KEY 
          echo done
        env:
          MAPS_KEY: ${{ secrets.MAPS_KEY }}
          WEATHER_KEY: ${{ secrets.WEATHER_KEY }}
          
